{"cells":[{"cell_type":"code","source":"!pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pandas","metadata":{"tags":[],"cell_id":"602d7b7698dd49a2984ec8fa9302df8f","source_hash":"d66d9d0e","execution_start":1677285399654,"execution_millis":4632,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[{"name":"stdout","text":"Requirement already satisfied: google-auth in /root/venv/lib/python3.10/site-packages (1.4.2)\nRequirement already satisfied: google-auth-oauthlib in /shared-libs/python3.10/py/lib/python3.10/site-packages (0.4.6)\nCollecting google-auth-httplib2\n  Using cached google_auth_httplib2-0.1.0-py2.py3-none-any.whl (9.3 kB)\nCollecting google-api-python-client\n  Using cached google_api_python_client-2.79.0-py2.py3-none-any.whl (11.0 MB)\nRequirement already satisfied: pandas in /shared-libs/python3.10/py/lib/python3.10/site-packages (1.2.5)\nRequirement already satisfied: cachetools>=2.0.0 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth) (5.2.0)\nRequirement already satisfied: pyasn1-modules>=0.2.1 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth) (0.2.8)\nRequirement already satisfied: six>=1.9.0 in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from google-auth) (1.16.0)\nRequirement already satisfied: rsa>=3.1.4 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth) (4.9)\nRequirement already satisfied: requests-oauthlib>=0.7.0 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth-oauthlib) (1.3.1)\nRequirement already satisfied: httplib2>=0.15.0 in /root/venv/lib/python3.10/site-packages (from google-auth-httplib2) (0.21.0)\nRequirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-api-python-client) (2.10.2)\nRequirement already satisfied: uritemplate<5,>=3.0.1 in /root/venv/lib/python3.10/site-packages (from google-api-python-client) (3.0.1)\nCollecting google-auth\n  Downloading google_auth-2.16.1-py2.py3-none-any.whl (177 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m177.2/177.2 kB\u001b[0m \u001b[31m24.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hRequirement already satisfied: python-dateutil>=2.7.3 in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from pandas) (2.8.2)\nRequirement already satisfied: pytz>=2017.3 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from pandas) (2022.5)\nRequirement already satisfied: numpy>=1.16.5 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from pandas) (1.23.4)\nRequirement already satisfied: requests<3.0.0dev,>=2.18.0 in /root/venv/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2.21.0)\nRequirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (1.56.4)\nRequirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (3.19.6)\nRequirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from httplib2>=0.15.0->google-auth-httplib2) (3.0.9)\nRequirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth) (0.4.8)\nRequirement already satisfied: oauthlib>=3.0.0 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)\nRequirement already satisfied: chardet<3.1.0,>=3.0.2 in /root/venv/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (3.0.4)\nRequirement already satisfied: certifi>=2017.4.17 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2022.9.24)\nRequirement already satisfied: urllib3<1.25,>=1.21.1 in /root/venv/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (1.24.3)\nCollecting idna<2.9,>=2.5\n  Using cached idna-2.8-py2.py3-none-any.whl (58 kB)\nInstalling collected packages: idna, google-auth, google-auth-httplib2, google-api-python-client\n  Attempting uninstall: idna\n    Found existing installation: idna 3.4\n    Not uninstalling idna at /shared-libs/python3.10/py-core/lib/python3.10/site-packages, outside environment /root/venv\n    Can't uninstall 'idna'. No files were found to uninstall.\n  Attempting uninstall: google-auth\n    Found existing installation: google-auth 1.4.2\n    Uninstalling google-auth-1.4.2:\n      Successfully uninstalled google-auth-1.4.2\nSuccessfully installed google-api-python-client-2.79.0 google-auth-2.16.1 google-auth-httplib2-0.1.0 idna-2.8\n\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip available: \u001b[0m\u001b[31;49m22.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m23.0.1\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n","output_type":"stream"}],"execution_count":1},{"cell_type":"code","source":"pip install --upgrade google-auth-oauthlib==0.4.4","metadata":{"tags":[],"cell_id":"55ccaa0d07ee42a080051e3bcc89dbc0","source_hash":"24b79acc","execution_start":1677285404289,"execution_millis":3493,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[{"name":"stdout","text":"Collecting google-auth-oauthlib==0.4.4\n  Downloading google_auth_oauthlib-0.4.4-py2.py3-none-any.whl (18 kB)\nRequirement already satisfied: google-auth>=1.0.0 in /root/venv/lib/python3.10/site-packages (from google-auth-oauthlib==0.4.4) (2.16.1)\nRequirement already satisfied: requests-oauthlib>=0.7.0 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth-oauthlib==0.4.4) (1.3.1)\nRequirement already satisfied: six>=1.9.0 in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from google-auth>=1.0.0->google-auth-oauthlib==0.4.4) (1.16.0)\nRequirement already satisfied: rsa<5,>=3.1.4 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth>=1.0.0->google-auth-oauthlib==0.4.4) (4.9)\nRequirement already satisfied: cachetools<6.0,>=2.0.0 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth>=1.0.0->google-auth-oauthlib==0.4.4) (5.2.0)\nRequirement already satisfied: pyasn1-modules>=0.2.1 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth>=1.0.0->google-auth-oauthlib==0.4.4) (0.2.8)\nRequirement already satisfied: requests>=2.0.0 in /root/venv/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib==0.4.4) (2.21.0)\nRequirement already satisfied: oauthlib>=3.0.0 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib==0.4.4) (3.2.2)\nRequirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.0->google-auth-oauthlib==0.4.4) (0.4.8)\nRequirement already satisfied: urllib3<1.25,>=1.21.1 in /root/venv/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib==0.4.4) (1.24.3)\nRequirement already satisfied: certifi>=2017.4.17 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib==0.4.4) (2022.9.24)\nRequirement already satisfied: chardet<3.1.0,>=3.0.2 in /root/venv/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib==0.4.4) (3.0.4)\nCollecting idna<2.9,>=2.5\n  Using cached idna-2.8-py2.py3-none-any.whl (58 kB)\nInstalling collected packages: idna, google-auth-oauthlib\n  Attempting uninstall: idna\n    Found existing installation: idna 3.4\n    Uninstalling idna-3.4:\n\u001b[31mERROR: Could not install packages due to an OSError: [Errno 30] Read-only file system: 'METADATA'\n\u001b[0m\u001b[31m\n\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip available: \u001b[0m\u001b[31;49m22.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m23.0.1\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython -m pip install --upgrade pip\u001b[0m\nNote: you may need to restart the kernel to use updated packages.\n","output_type":"stream"}],"execution_count":2},{"cell_type":"code","source":"!pip install google-auth-httplib2","metadata":{"tags":[],"cell_id":"434f96cb2c184fe78f545efef39e5daa","source_hash":"daee9d38","execution_start":1677285407786,"execution_millis":3227,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[{"name":"stdout","text":"Requirement already satisfied: google-auth-httplib2 in /root/venv/lib/python3.10/site-packages (0.1.0)\nRequirement already satisfied: six in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from google-auth-httplib2) (1.16.0)\nRequirement already satisfied: httplib2>=0.15.0 in /root/venv/lib/python3.10/site-packages (from google-auth-httplib2) (0.21.0)\nRequirement already satisfied: google-auth in /root/venv/lib/python3.10/site-packages (from google-auth-httplib2) (2.16.1)\nRequirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from httplib2>=0.15.0->google-auth-httplib2) (3.0.9)\nRequirement already satisfied: pyasn1-modules>=0.2.1 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google-auth-httplib2) (0.2.8)\nRequirement already satisfied: cachetools<6.0,>=2.0.0 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google-auth-httplib2) (5.2.0)\nRequirement already satisfied: rsa<5,>=3.1.4 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google-auth-httplib2) (4.9)\nRequirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth->google-auth-httplib2) (0.4.8)\n\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip available: \u001b[0m\u001b[31;49m22.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m23.0.1\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n","output_type":"stream"}],"execution_count":3},{"cell_type":"code","source":"!pip uninstall google-auth-httplib2 -y\n!pip install google-auth-httplib2","metadata":{"tags":[],"cell_id":"c815a3bf7105415a97babb7c00df069e","source_hash":"9880a5d1","execution_start":1677285411031,"execution_millis":4621,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[{"name":"stdout","text":"Found existing installation: google-auth-httplib2 0.1.0\nUninstalling google-auth-httplib2-0.1.0:\n  Successfully uninstalled google-auth-httplib2-0.1.0\nCollecting google-auth-httplib2\n  Using cached google_auth_httplib2-0.1.0-py2.py3-none-any.whl (9.3 kB)\nRequirement already satisfied: google-auth in /root/venv/lib/python3.10/site-packages (from google-auth-httplib2) (2.16.1)\nRequirement already satisfied: six in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from google-auth-httplib2) (1.16.0)\nRequirement already satisfied: httplib2>=0.15.0 in /root/venv/lib/python3.10/site-packages (from google-auth-httplib2) (0.21.0)\nRequirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from httplib2>=0.15.0->google-auth-httplib2) (3.0.9)\nRequirement already satisfied: cachetools<6.0,>=2.0.0 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google-auth-httplib2) (5.2.0)\nRequirement already satisfied: pyasn1-modules>=0.2.1 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google-auth-httplib2) (0.2.8)\nRequirement already satisfied: rsa<5,>=3.1.4 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google-auth-httplib2) (4.9)\nRequirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth->google-auth-httplib2) (0.4.8)\nInstalling collected packages: google-auth-httplib2\nSuccessfully installed google-auth-httplib2-0.1.0\n\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip available: \u001b[0m\u001b[31;49m22.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m23.0.1\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n","output_type":"stream"}],"execution_count":4},{"cell_type":"code","source":"!pip install google.auth.httplib2==0.1.0","metadata":{"tags":[],"cell_id":"a7efadc679ab4aa9a786db3f54d36dd6","source_hash":"1e2169cc","execution_start":1677285423504,"execution_millis":3017,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[{"name":"stdout","text":"Requirement already satisfied: google.auth.httplib2==0.1.0 in /root/venv/lib/python3.10/site-packages (0.1.0)\nRequirement already satisfied: six in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from google.auth.httplib2==0.1.0) (1.16.0)\nRequirement already satisfied: google-auth in /root/venv/lib/python3.10/site-packages (from google.auth.httplib2==0.1.0) (2.16.1)\nRequirement already satisfied: httplib2>=0.15.0 in /root/venv/lib/python3.10/site-packages (from google.auth.httplib2==0.1.0) (0.21.0)\nRequirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from httplib2>=0.15.0->google.auth.httplib2==0.1.0) (3.0.9)\nRequirement already satisfied: pyasn1-modules>=0.2.1 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google.auth.httplib2==0.1.0) (0.2.8)\nRequirement already satisfied: cachetools<6.0,>=2.0.0 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google.auth.httplib2==0.1.0) (5.2.0)\nRequirement already satisfied: rsa<5,>=3.1.4 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google.auth.httplib2==0.1.0) (4.9)\nRequirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth->google.auth.httplib2==0.1.0) (0.4.8)\n\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip available: \u001b[0m\u001b[31;49m22.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m23.0.1\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n","output_type":"stream"}],"execution_count":7},{"cell_type":"code","source":"!pip install google.auth.httplib2==0.1.0","metadata":{"tags":[],"cell_id":"4645c3a130bc4b9a92a1a4171eabbc6a","source_hash":"1e2169cc","execution_start":1677285437871,"execution_millis":2826,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[{"name":"stdout","text":"Requirement already satisfied: google.auth.httplib2==0.1.0 in /root/venv/lib/python3.10/site-packages (0.1.0)\nRequirement already satisfied: google-auth in /root/venv/lib/python3.10/site-packages (from google.auth.httplib2==0.1.0) (2.16.1)\nRequirement already satisfied: httplib2>=0.15.0 in /root/venv/lib/python3.10/site-packages (from google.auth.httplib2==0.1.0) (0.21.0)\nRequirement already satisfied: six in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from google.auth.httplib2==0.1.0) (1.16.0)\nRequirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /shared-libs/python3.10/py-core/lib/python3.10/site-packages (from httplib2>=0.15.0->google.auth.httplib2==0.1.0) (3.0.9)\nRequirement already satisfied: cachetools<6.0,>=2.0.0 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google.auth.httplib2==0.1.0) (5.2.0)\nRequirement already satisfied: rsa<5,>=3.1.4 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google.auth.httplib2==0.1.0) (4.9)\nRequirement already satisfied: pyasn1-modules>=0.2.1 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from google-auth->google.auth.httplib2==0.1.0) (0.2.8)\nRequirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /shared-libs/python3.10/py/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth->google.auth.httplib2==0.1.0) (0.4.8)\n\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip available: \u001b[0m\u001b[31;49m22.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m23.0.1\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n","output_type":"stream"}],"execution_count":10},{"cell_type":"code","source":"import os\nimport pandas as pd\nfrom google.oauth2 import service_account\nfrom google.auth.transport.requests import AuthorizedSession\nimport google.auth.exceptions\nimport google.auth.httplib2\nimport httplib2\n\n# replace with your own credentials file path\ncredentials_file = os.environ.get(\"GOOGLE_APPLICATION_CREDENTIALS\", \"/work/camp-claremont-eef0a71b208c.json\")\n\n# create a credentials object from the service account file\ncreds = service_account.Credentials.from_service_account_file(credentials_file, scopes=[\"https://www.googleapis.com/auth/drive\"])\n\n# create an authorized session object\ntry:\n    session = AuthorizedSession(creds)\nexcept google.auth.exceptions.TransportError as error:\n    print(f\"An error occurred: {error}\")\n    session = None\n\n# ID of the file to update\nfile_id = \"1MNW8xJ5l9aj0njmdDuACcFy6Aa7BGQ3g\"\n\n# export the file as CSV\nexport_url = f\"https://drive.google.com/uc?id={file_id}&export=download\"\nresp = session.get(export_url)\n\n# read the downloaded CSV file into a pandas dataframe\ndf = pd.read_csv(resp.content.decode(\"utf-8\"))\n\n# create a new row to add to the dataframe\ndf_row = pd.DataFrame([[\"John\", \"Doe\", \"johndoe@gmail.com\"]], columns=[\"First Name\", \"Last Name\", \"Email\"])\n\n# add the new row to the dataframe\ndf = df.append(df_row, ignore_index=True)\n\n# convert the modified dataframe back to a CSV file and upload to Google Drive\nfile_metadata = {\"name\": \"updated_file.csv\", \"parents\": [], \"mimeType\": \"text/csv\"} # modify the file name and MIME type if needed\nmedia = pd.DataFrame.to_csv(df, index=False).encode(\"utf-8\")\ntry:\n    resp = session.put(f\"https://www.googleapis.com/upload/drive/v3/files/{file_id}?uploadType=media\",\n                       headers=file_metadata, data=media)\n    print(f\"File updated: {resp.json()['name']}\")\nexcept google.auth.exceptions.TransportError as error:\n    print(f\"An error occurred: {error}\")\n    resp = None","metadata":{"tags":[],"cell_id":"9ab038bc1c2c4a39b48e2f38c89c76ec","source_hash":"92fe919a","execution_start":1677285443755,"execution_millis":25,"deepnote_to_be_reexecuted":false,"deepnote_cell_type":"code"},"outputs":[{"output_type":"error","ename":"ModuleNotFoundError","evalue":"No module named 'google.auth.httplib2'","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)","Cell \u001b[0;32mIn [11], line 6\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mgoogle\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mauth\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mtransport\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mrequests\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m AuthorizedSession\n\u001b[1;32m      5\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mgoogle\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mauth\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mexceptions\u001b[39;00m\n\u001b[0;32m----> 6\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mgoogle\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mauth\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mhttplib2\u001b[39;00m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mhttplib2\u001b[39;00m\n\u001b[1;32m      9\u001b[0m \u001b[38;5;66;03m# replace with your own credentials file path\u001b[39;00m\n","\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'google.auth.httplib2'"]}],"execution_count":11},{"cell_type":"markdown","source":"<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=2bcc5d52-b4eb-42dd-a50f-c9803ec58156' target=\"_blank\">\n<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iODBweCIgaGVpZ2h0PSI4MHB4IiB2aWV3Qm94PSIwIDAgODAgODAiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgICA8IS0tIEdlbmVyYXRvcjogU2tldGNoIDU0LjEgKDc2NDkwKSAtIGh0dHBzOi8vc2tldGNoYXBwLmNvbSAtLT4KICAgIDx0aXRsZT5Hcm91cCAzPC90aXRsZT4KICAgIDxkZXNjPkNyZWF0ZWQgd2l0aCBTa2V0Y2guPC9kZXNjPgogICAgPGcgaWQ9IkxhbmRpbmciIHN0cm9rZT0ibm9uZSIgc3Ryb2tlLXdpZHRoPSIxIiBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPgogICAgICAgIDxnIGlkPSJBcnRib2FyZCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTEyMzUuMDAwMDAwLCAtNzkuMDAwMDAwKSI+CiAgICAgICAgICAgIDxnIGlkPSJHcm91cC0zIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxMjM1LjAwMDAwMCwgNzkuMDAwMDAwKSI+CiAgICAgICAgICAgICAgICA8cG9seWdvbiBpZD0iUGF0aC0yMCIgZmlsbD0iIzAyNjVCNCIgcG9pbnRzPSIyLjM3NjIzNzYyIDgwIDM4LjA0NzY2NjcgODAgNTcuODIxNzgyMiA3My44MDU3NTkyIDU3LjgyMTc4MjIgMzIuNzU5MjczOSAzOS4xNDAyMjc4IDMxLjY4MzE2ODMiPjwvcG9seWdvbj4KICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0zNS4wMDc3MTgsODAgQzQyLjkwNjIwMDcsNzYuNDU0OTM1OCA0Ny41NjQ5MTY3LDcxLjU0MjI2NzEgNDguOTgzODY2LDY1LjI2MTk5MzkgQzUxLjExMjI4OTksNTUuODQxNTg0MiA0MS42NzcxNzk1LDQ5LjIxMjIyODQgMjUuNjIzOTg0Niw0OS4yMTIyMjg0IEMyNS40ODQ5Mjg5LDQ5LjEyNjg0NDggMjkuODI2MTI5Niw0My4yODM4MjQ4IDM4LjY0NzU4NjksMzEuNjgzMTY4MyBMNzIuODcxMjg3MSwzMi41NTQ0MjUgTDY1LjI4MDk3Myw2Ny42NzYzNDIxIEw1MS4xMTIyODk5LDc3LjM3NjE0NCBMMzUuMDA3NzE4LDgwIFoiIGlkPSJQYXRoLTIyIiBmaWxsPSIjMDAyODY4Ij48L3BhdGg+CiAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMCwzNy43MzA0NDA1IEwyNy4xMTQ1MzcsMC4yNTcxMTE0MzYgQzYyLjM3MTUxMjMsLTEuOTkwNzE3MDEgODAsMTAuNTAwMzkyNyA4MCwzNy43MzA0NDA1IEM4MCw2NC45NjA0ODgyIDY0Ljc3NjUwMzgsNzkuMDUwMzQxNCAzNC4zMjk1MTEzLDgwIEM0Ny4wNTUzNDg5LDc3LjU2NzA4MDggNTMuNDE4MjY3Nyw3MC4zMTM2MTAzIDUzLjQxODI2NzcsNTguMjM5NTg4NSBDNTMuNDE4MjY3Nyw0MC4xMjg1NTU3IDM2LjMwMzk1NDQsMzcuNzMwNDQwNSAyNS4yMjc0MTcsMzcuNzMwNDQwNSBDMTcuODQzMDU4NiwzNy43MzA0NDA1IDkuNDMzOTE5NjYsMzcuNzMwNDQwNSAwLDM3LjczMDQ0MDUgWiIgaWQ9IlBhdGgtMTkiIGZpbGw9IiMzNzkzRUYiPjwvcGF0aD4KICAgICAgICAgICAgPC9nPgogICAgICAgIDwvZz4KICAgIDwvZz4KPC9zdmc+' > </img>\nCreated in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>","metadata":{"created_in_deepnote_cell":true,"deepnote_cell_type":"markdown"}}],"nbformat":4,"nbformat_minor":0,"metadata":{"deepnote":{},"orig_nbformat":2,"deepnote_notebook_id":"ef41932e16ff4647a201fdcb3191c13e","deepnote_execution_queue":[]}}